project:
  type: website
  output-dir: docs

website:
  title: "Canopy Nine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rvasec14/
        text: RVASec 14 LLMs for Hackers
#      - about.qmd

format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css
    toc: true



